import fs from 'fs';
import path from 'path';
import ignore from 'ignore';

interface InitRule {
  ctxignoreLine: string;
  match: (relPath: string) => boolean;
}

const INIT_RULES: InitRule[] = [
  { ctxignoreLine: 'node_modules/', match: (r) => r.startsWith('node_modules/') || r.includes('/node_modules/') },
  { ctxignoreLine: '*.lock',        match: (r) => /\.lock$/.test(r) || r === 'package-lock.json' || r === 'pnpm-lock.yaml' },
  { ctxignoreLine: 'dist/',         match: (r) => r.startsWith('dist/') },
  { ctxignoreLine: 'build/',        match: (r) => r.startsWith('build/') },
  { ctxignoreLine: 'out/',          match: (r) => r.startsWith('out/') },
  { ctxignoreLine: '.next/',        match: (r) => r.startsWith('.next/') },
  { ctxignoreLine: '.nuxt/',        match: (r) => r.startsWith('.nuxt/') },
  { ctxignoreLine: '__pycache__/',  match: (r) => r.includes('__pycache__/') },
  { ctxignoreLine: '*.pyc',         match: (r) => r.endsWith('.pyc') },
  { ctxignoreLine: '*.min.js',      match: (r) => r.endsWith('.min.js') },
  { ctxignoreLine: '*.min.css',     match: (r) => r.endsWith('.min.css') },
  { ctxignoreLine: '*.map',         match: (r) => r.endsWith('.map') },
  { ctxignoreLine: 'coverage/',     match: (r) => r.startsWith('coverage/') || r.startsWith('.nyc_output/') },
];

export function generateCtxignore(root: string): string[] {
  const gitignorePath = path.join(root, '.gitignore');
  const ig = ignore();
  if (fs.existsSync(gitignorePath)) {
    ig.add(fs.readFileSync(gitignorePath, 'utf8'));
  }

  const detected = new Set<string>();

  function walk(dir: string): void {
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }

    for (const entry of entries) {
      const abs = path.join(dir, entry.name);
      const rel = path.relative(root, abs).split(path.sep).join('/');
      if (rel.startsWith('.git/') || rel === '.git') continue;

      const testRel = entry.isDirectory() ? rel + '/' : rel;
      for (const rule of INIT_RULES) {
        if (rule.match(testRel) || rule.match(rel)) {
          detected.add(rule.ctxignoreLine);
          break;
        }
      }

      if (entry.isDirectory()) {
        walk(abs);
      }
    }
  }

  walk(root);

  return Array.from(detected).filter((line) => {
    const testPath = line.endsWith('/') ? line + 'placeholder' : line.replace('*', 'test');
    return !ig.ignores(testPath);
  });
}

export function writeCtxignore(root: string, patterns: string[]): void {
  const content = [
    '# Generated by fitcheck init',
    '# Remove lines you want included in AI context',
    '',
    ...patterns,
    '',
  ].join('\n');
  fs.writeFileSync(path.join(root, '.ctxignore'), content, 'utf8');
}
